// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzmAJqGv0Y5XgK5n_xegBiuvIyt8zXeGg',
    appId: '1:673679708182:web:96a694035e3bd35168e537',
    messagingSenderId: '673679708182',
    projectId: 'app-test-e5482',
    authDomain: 'app-test-e5482.firebaseapp.com',
    storageBucket: 'app-test-e5482.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtxKUmuwYZXW0iDB2DmBkjemycABKzS_A',
    appId: '1:673679708182:android:23a91ad450c7baed68e537',
    messagingSenderId: '673679708182',
    projectId: 'app-test-e5482',
    storageBucket: 'app-test-e5482.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ-3wRnh3dMFKNxc-ldZNuA10GlItKDv8',
    appId: '1:673679708182:ios:2e69245bf39ee80568e537',
    messagingSenderId: '673679708182',
    projectId: 'app-test-e5482',
    storageBucket: 'app-test-e5482.appspot.com',
    iosBundleId: 'com.example.appPrueba1306',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ-3wRnh3dMFKNxc-ldZNuA10GlItKDv8',
    appId: '1:673679708182:ios:2e69245bf39ee80568e537',
    messagingSenderId: '673679708182',
    projectId: 'app-test-e5482',
    storageBucket: 'app-test-e5482.appspot.com',
    iosBundleId: 'com.example.appPrueba1306',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzmAJqGv0Y5XgK5n_xegBiuvIyt8zXeGg',
    appId: '1:673679708182:web:73e1862342355b2a68e537',
    messagingSenderId: '673679708182',
    projectId: 'app-test-e5482',
    authDomain: 'app-test-e5482.firebaseapp.com',
    storageBucket: 'app-test-e5482.appspot.com',
  );

}